# Generated by Django 6.0.2 on 2026-02-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='live_link',
        ),
        migrations.AddField(
            model_name='project',
            name='ive_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
