# Generated by Django 6.0.2 on 2026-02-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_live_link_project_ive_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='ive_link',
            new_name='live_link',
        ),
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
