# Generated by Django 6.0.2 on 2026-02-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_siteprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='headline',
            field=models.CharField(default="Hi, I'm Sunny 👋", max_length=120),
        ),
    ]
