# Generated by Django 6.0.2 on 2026-02-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='order',
        ),
    ]
