# Generated by Django 6.0.2 on 2026-02-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_skill_options_remove_skill_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'name']},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='note',
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('learning', 'Learning'), ('good', 'Good'), ('mid', 'Intermediate')], default='learning', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
